spring.jpa.open-in-view: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mayikt?useSSL=false&serverTimezone=Asia/Shanghai
    username: root     # ????????
    password: root     # ???????
  jpa:
    hibernate:
      ddl-auto: none   # ? ?????????????? todolist ?
    show-sql: true
